### ISSUE TITLE
AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by emilsenkel** [marco-buratto/signage-orchestrator#1]
Dear Marco, 

I have encountered a problem. I can navigate through the different tabs, but I keep getting this error and I can't add a slideshow playlist. Do you know how I can solve this problem?

Kind regards

Emil Senkel

AxiosError: Request failed with status code 500
<img width="1360" alt="Screenshot 2023-11-29 at 14 33 15" src="https://github.com/marco-buratto/signage-orchestrator/assets/19310584/b284d0f9-c8ca-4240-88f2-a064821c1185">

**Comment by marco-buratto** [comment]
Hi,

please list all your steps from a clean system. 
Which operating system have you installed Signage Orchestrator in?
Also, have a look at server logs: ssh into the host/vm where Signage Orchestrator is installed, then do the following, as root, before performing the action which gives you the error:

tail -f /var/log/syslog

Check system date is correct as well.

**Comment by phalconavatar** [comment]
I'm going to hop on here with the same issue.

Install OS, Install dependencies, Install Signage Orchestrator as per the instructions in the readme. Open via browser and any page load generates this error. 

Running on a PI3b. Have tried a couple builds of Debian 12 and the current raspberry pi os based on bookworm

syslog shows no file or directory

Checked date and time are accurate

**Comment by phenbach** [comment]
I am having this same issue. Has anyone come up with a fix?

**Comment by marco-buratto** [comment]
Which operating system have you installed Signage Orchestrator in?

The only operating system I tested is a x64 Debian 12, not Raspbian/Raspberry Pi. 
Please use a host or vm with it installed.

I'm having a look at installing into a Raspbian OS soon.
