### ISSUE TITLE
Player (Raspberry) can't be found

### ISSUE THREAD

**Issue by diesel90** [marco-buratto/signage-orchestrator#2]
Hi,

the Signage Orchestrator was installed successfully on a VM (Debian 12.5 64 Bit). I get access to the web interface.
When I want to "register" the player, after downloading the player-connector script to the Raspberry via ssh and running it with the commands, there is no player shown in the player menu of the web interface.
The Raspberry Pi is a new one (RP5). Is there an issue with the new Raspberry or is there a list which Raspberry Pi I should use?

Thank you

**Comment by marco-buratto** [comment]
Please first launch /usr/bin/player.sh (as root) from within the Pi player and check that the Orchestrator has sent a response with: cat /tmp/orchestrator.response

**Comment by marco-buratto** [comment]
I've added a DEBUG document.

**Comment by marco-buratto** [comment]
I've added a DEBUG file in the documentation, please refer to it.
